import type { Metadata } from "next";
import { Outfit, Raleway } from "next/font/google";
import "./globals.css";

import ReduxProvider from "@/context/ReduxProvider";
import MobileNav from "@/components/ui/MobileNav";
import Navbar from "@/components/ui/Navbar";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["400", "700"], // Choose the weights you need for headings
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["400", "500"], // Choose the weights you need for small text
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${raleway.variable} antialiased`}>
        <ReduxProvider>
          <Navbar />
          <MobileNav />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
